consolidate-commits = true
consolidate-pushes = true
dev-version = false
sign-commit = true
sign-tag = true
shared-version = true
allow-branch = ["trunk"]
pre-release-commit-message = "Version {{version}}"