name: Changelog

on:
  pull_request:

jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    name: Changelog Change

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: check changelog
        run: |
          if git diff --quiet origin/${{ github.base_ref }} HEAD CHANGELOG.md; then
              echo "Changelog unchanged!"
              exit 1
          fi
